# Generated by Django 5.2.7 on 2025-11-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('published_date', models.DateField(verbose_name='Дата публикации')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('pages', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('language', models.CharField(max_length=100, verbose_name='Язык')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(verbose_name='Количество в наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
            },
        ),
    ]
